/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author David Torrez
 */
public class Pmain extends javax.swing.JFrame {

    /**
     * Creates new form Pmain
     */
    public Pmain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnGestionarClientes = new javax.swing.JButton();
        jbtnGestionarInstructor = new javax.swing.JButton();
        jbtnGestionarSalas = new javax.swing.JButton();
        jbtnGestionarDisciplinas = new javax.swing.JButton();
        jbtnGestionarInscripcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA DE GIMNASIO REY DAVID");

        jbtnGestionarClientes.setText("Gestionar Clientes");
        jbtnGestionarClientes.setActionCommand("Gestionar Cliente");
        jbtnGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionarClientesActionPerformed(evt);
            }
        });

        jbtnGestionarInstructor.setText("Gestionar Instructores");
        jbtnGestionarInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionarInstructorActionPerformed(evt);
            }
        });

        jbtnGestionarSalas.setText("GestionarSalas");
        jbtnGestionarSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionarSalasActionPerformed(evt);
            }
        });

        jbtnGestionarDisciplinas.setText("Gestionar Disciplinas");
        jbtnGestionarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionarDisciplinasActionPerformed(evt);
            }
        });

        jbtnGestionarInscripcion.setText("Gestionar Inscripcion");
        jbtnGestionarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGestionarInscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnGestionarClientes)
                            .addComponent(jbtnGestionarDisciplinas))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnGestionarInstructor)
                                .addGap(75, 75, 75)
                                .addComponent(jbtnGestionarSalas))
                            .addComponent(jbtnGestionarInscripcion))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGestionarClientes)
                    .addComponent(jbtnGestionarInstructor)
                    .addComponent(jbtnGestionarSalas))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGestionarDisciplinas)
                    .addComponent(jbtnGestionarInscripcion))
                .addGap(0, 131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionarClientesActionPerformed
        // TODO add your handling code here:
        new Pcliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnGestionarClientesActionPerformed

    private void jbtnGestionarInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionarInstructorActionPerformed
        // TODO add your handling code here:
        new Pinstructor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnGestionarInstructorActionPerformed

    private void jbtnGestionarSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionarSalasActionPerformed
        // TODO add your handling code here:
        new Psala().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnGestionarSalasActionPerformed

    private void jbtnGestionarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionarDisciplinasActionPerformed
        // TODO add your handling code here:
        new Pdisciplina().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnGestionarDisciplinasActionPerformed

    private void jbtnGestionarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGestionarInscripcionActionPerformed
        // TODO add your handling code here:
        new Pinscripcion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnGestionarInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnGestionarClientes;
    private javax.swing.JButton jbtnGestionarDisciplinas;
    private javax.swing.JButton jbtnGestionarInscripcion;
    private javax.swing.JButton jbtnGestionarInstructor;
    private javax.swing.JButton jbtnGestionarSalas;
    // End of variables declaration//GEN-END:variables
}
